apiVersion: v1
kind: Service
metadata:
  name: secure-app-service
  labels:
    app: secure-app
spec:
  type: NodePort
  selector:
    app: secure-app
  ports:
    - name: "3000"
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
